
#ifndef USER_OPTION_ENUM
#define USER_OPTION_ENUM
enum class UserOption {
  LIST_ITEMS = 1,
  CREATE_NEW_ITEM,
  EXAMINE_ITEM,
  DELETE_ITEM,
  EXIT,
  INVALID,
  FIRST = LIST_ITEMS,
  LAST = INVALID
};
#endif
